"use client";

import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowLeft, FileCheck2, Send } from "lucide-react";
import { createResource, listResource, updateResource } from "@/lib/client/dataApi";

type ProjectFile={id:string;project_id:string|null;project_name:string|null;name:string;category:string;revision:string;uploaded_by_id:string|null;uploaded_by_name:string|null;description:string;file_name:string|null;status:string;is_current:boolean};
type Approval={id:string};

export default function NewApprovalPage(){
  const router=useRouter(); const [files,setFiles]=useState<ProjectFile[]>([]); const [fileId,setFileId]=useState(""); const [description,setDescription]=useState(""); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState("");
  useEffect(()=>{void listResource<ProjectFile>("files",undefined,500).then((response)=>setFiles(response.data.filter((item)=>item.is_current!==false))).catch((cause)=>setError(cause instanceof Error?cause.message:"Could not load files.")).finally(()=>setLoading(false))},[]);
  const selected=useMemo(()=>files.find((item)=>item.id===fileId),[files,fileId]);
  async function submit(event:FormEvent){event.preventDefault();if(!selected)return;setSaving(true);setError("");try{const created=await createResource<Approval>("approvals",{project_id:selected.project_id,project_name:selected.project_name,title:selected.name,type:approvalType(selected.category),revision:selected.revision,status:"Pending",description:description.trim()||selected.description,file_id:selected.id});await updateResource("files",{id:selected.id,status:"Pending Approval"});router.push(`/app/admin/approvals/${created.data.id}`);router.refresh()}catch(cause){setError(cause instanceof Error?cause.message:"Could not create approval.")}finally{setSaving(false)}}
  return <main className="min-h-screen bg-[#050505] text-white"><div className="mx-auto max-w-3xl px-6 py-8 lg:px-10"><Link href="/app/admin/approvals" className="inline-flex items-center gap-2 text-[10px] uppercase tracking-[0.2em] text-white/30 hover:text-white"><ArrowLeft size={13}/>Approvals</Link><div className="mt-8"><p className="text-[9px] uppercase tracking-[0.25em] text-white/25">Shared workflow</p><h1 className="mt-2 text-3xl font-light">Submit Approval</h1><p className="mt-2 text-sm text-white/35">Select a shared project file and submit its current revision for review.</p></div>{error&&<p role="alert" className="mt-5 rounded-xl border border-red-400/30 bg-red-400/10 p-4 text-sm text-red-200">{error}</p>}<form onSubmit={submit} className="mt-10 space-y-6 rounded-2xl border border-white/10 bg-white/[0.02] p-6"><label className="block"><span className="mb-2 block text-[9px] uppercase tracking-[0.2em] text-white/30">Project file</span><select value={fileId} onChange={(event)=>setFileId(event.target.value)} className="w-full rounded-xl border border-white/10 bg-[#111] px-4 py-3 text-sm"><option value="">{loading?"Loading files…":"Choose a file"}</option>{files.map((file)=><option key={file.id} value={file.id}>{file.project_name||"No project"} — {file.name} ({file.revision})</option>)}</select></label>{selected&&<div className="rounded-xl border border-white/10 bg-white/[0.03] p-5"><div className="flex items-center gap-3"><FileCheck2 size={18} className="text-white/40"/><div><p className="text-sm">{selected.name}</p><p className="mt-1 text-xs text-white/35">{selected.project_name} · {selected.category} · {selected.revision}</p></div></div></div>}<label className="block"><span className="mb-2 block text-[9px] uppercase tracking-[0.2em] text-white/30">Submission note</span><textarea value={description} onChange={(event)=>setDescription(event.target.value)} rows={5} placeholder="Add a note for the reviewer…" className="w-full resize-none rounded-xl border border-white/10 bg-white/[0.03] px-4 py-3 text-sm outline-none placeholder:text-white/20"/></label><button disabled={!selected||saving} className="inline-flex w-full items-center justify-center gap-2 rounded-xl bg-white px-5 py-3 text-sm font-medium text-black disabled:opacity-40"><Send size={14}/>{saving?"Submitting…":"Submit revision for approval"}</button></form></div></main>;
}

function approvalType(category:string){return category.includes("Drawing")?"Drawing":category==="Render"?"Render":"Document"}
