export default function CompletenessPage(){
 const done=["Public website locked","Project / task / file / approval foundation","Site management","Finance & profitability","Client portal","Calendar & notifications","Reports / permissions / audit foundation","AI Project Brain","Local Qwen Vision","Local Z-Image-Turbo + ComfyUI","AI Agents","AI Actions","Predictive project intelligence","Construction controls: RFI / Submittal / Material / Inspection / NCR / Snag / Handover","Command Center","CRM / Contracts / Procurement / QA-QC / HSE foundation"];
 const production=["Postgres database + migrations","Secure database sessions","S3 signed-upload integration","Realtime event-stream foundation","Backup + guarded restore scripts","Granular server-side authorization","GitHub Actions build CI"];
 const remaining=["Password-reset delivery (needs an email provider)","Configure S3 bucket credentials for production uploads","Email / WhatsApp / calendar provider integrations","Production observability / error tracking","Complete localStorage-to-Postgres migration for every workspace module","Production deployment + domain / SSL","AI audit, usage controls and model governance"];
 return <main className="min-h-screen bg-white px-6 py-10 text-black lg:px-12"><div className="mx-auto max-w-6xl">
  <p className="text-[10px] uppercase tracking-[0.3em] text-black/40">Mason & Arc / System Status</p><h1 className="mt-3 text-4xl font-medium">What is finished — what remains</h1>
  <div className="mt-8 grid gap-6 lg:grid-cols-2"><section className="rounded-xl border border-black/10 p-6"><h2 className="font-medium">Studio OS foundation</h2><div className="mt-5 space-y-3">{done.map(x=><div key={x} className="flex gap-3 text-sm"><span>✓</span><span>{x}</span></div>)}</div></section>
  <section className="rounded-xl border border-black/10 p-6"><h2 className="font-medium">Production hardening — completed</h2><div className="mt-5 space-y-3">{production.map(x=><div key={x} className="flex gap-3 text-sm"><span>✓</span><span>{x}</span></div>)}</div><h2 className="mt-8 border-t border-black/10 pt-6 font-medium">Still needs external setup or remaining migration</h2><div className="mt-5 space-y-3">{remaining.map(x=><div key={x} className="flex gap-3 text-sm"><span>○</span><span>{x}</span></div>)}</div></section></div>
  <div className="mt-6 rounded-xl bg-black p-6 text-white"><p className="text-sm font-medium">Important</p><p className="mt-2 text-sm leading-6 text-white/70">The current Studio OS is a strong local prototype/operational system. The remaining list is the work required to make it a secure production SaaS used by multiple people and devices. The public Mason & Arc website remains separate and locked.</p></div>
 </div></main>
}
