export default function CompletenessPage(){
 const done=["Public website locked","Project / task / file / approval foundation","Site management","Finance & profitability","Client portal","Calendar & notifications","Reports / permissions / audit foundation","AI Project Brain","Local Qwen Vision","Local Z-Image-Turbo + ComfyUI","AI Agents","AI Actions","Predictive project intelligence","Construction controls: RFI / Submittal / Material / Inspection / NCR / Snag / Handover","Command Center","CRM / Contracts / Procurement / QA-QC / HSE foundation"];
 const production=["Postgres database + migrations","Database sessions and sign-in rate limits","Password-reset pages and one-time expiring tokens","Gmail send-only OAuth implementation","S3 signed-upload API foundation","Realtime event-stream foundation","Backup + guarded restore scripts","Server-side authorization foundation","GitHub Actions build CI","Production deployment + domain / SSL","Mobile Workspace login and navigation","Direct office WhatsApp link (+20 1044007555)"];
 const remaining=["Complete Gmail consent and verify a real password-reset email reaches the inbox","Configure shared file storage and verify upload/download permissions","Calendar integration and automatic notification delivery","WhatsApp automation is disabled: API messages can incur fees","Production error monitoring and a verified backup restore","Complete localStorage-to-Postgres migration and test separate staff accounts","Secure office-computer connection for hosted AI Engineer access","AI audit, usage controls and model governance"];
 return <main className="min-h-screen bg-white px-6 py-10 text-black lg:px-12"><div className="mx-auto max-w-6xl">
  <p className="text-[10px] uppercase tracking-[0.3em] text-black/40">Mason & Arc / System Status</p><h1 className="mt-3 text-4xl font-medium">What is finished — what remains</h1>
  <div className="mt-8 grid gap-6 lg:grid-cols-2"><section className="rounded-xl border border-black/10 p-6"><h2 className="font-medium">Studio OS foundation</h2><div className="mt-5 space-y-3">{done.map(x=><div key={x} className="flex gap-3 text-sm"><span>✓</span><span>{x}</span></div>)}</div></section>
  <section className="rounded-xl border border-black/10 p-6"><h2 className="font-medium">Implemented foundations — not end-to-end certification</h2><div className="mt-5 space-y-3">{production.map(x=><div key={x} className="flex gap-3 text-sm"><span>✓</span><span>{x}</span></div>)}</div><h2 className="mt-8 border-t border-black/10 pt-6 font-medium">Required before full team rollout</h2><div className="mt-5 space-y-3">{remaining.map(x=><div key={x} className="flex gap-3 text-sm"><span>○</span><span>{x}</span></div>)}</div></section></div>
  <div className="mt-6 rounded-xl bg-black p-6 text-white"><p className="text-sm font-medium">Full team rollout is not ready yet</p><p className="mt-2 text-sm leading-6 text-white/70">Several workspace modules still save records in this browser only. Those changes are not reliably shared with colleagues or other devices. Do not use these modules as the only copy of live project data. Implemented integrations still need configuration and end-to-end tests. Gmail authorization status is shown in Settings.</p></div>
 </div></main>
}
