"use client";

import Link from "next/link";
import { useSearchParams, useRouter } from "next/navigation";
import { FormEvent, Suspense, useEffect, useState } from "react";
import { ArrowLeft, Save } from "lucide-react";

type Project={id:string;name:string;code:string;contract_value:string|null;budget:string|null;financial_currency:string|null};
const categories=["Contract","Payment","Design Cost","Site Cost","Material","Transportation","Software","Consultant","Other"];

function FinanceForm(){const query=useSearchParams();const router=useRouter();const requestedProject=query.get("project")||"";const [projects,setProjects]=useState<Project[]>([]);const [projectId,setProjectId]=useState(requestedProject);const [type,setType]=useState("Income");const [category,setCategory]=useState("Payment");const [description,setDescription]=useState("");const [amount,setAmount]=useState("");const [currency,setCurrency]=useState("EGP");const [date,setDate]=useState(new Date().toISOString().slice(0,10));const [status,setStatus]=useState("Received");const [contract,setContract]=useState("");const [budget,setBudget]=useState("");const [error,setError]=useState("");const [saving,setSaving]=useState(false);
useEffect(()=>{void(async()=>{const response=await fetch("/api/data/projects",{cache:"no-store",credentials:"include"});const data=await response.json().catch(()=>({}));if(!response.ok){setError(data.error||"Could not load projects.");return;}const loaded=data.data||[];setProjects(loaded);const initial=loaded.find((project:Project)=>project.id===requestedProject)||loaded[0];if(initial){setProjectId(initial.id);setContract(initial.contract_value??"");setBudget(initial.budget??"");setCurrency(initial.financial_currency||"EGP");}})()},[requestedProject]);
useEffect(()=>{const project=projects.find(item=>item.id===projectId);if(project){setContract(project.contract_value??"");setBudget(project.budget??"");setCurrency(project.financial_currency||"EGP");}},[projectId,projects]);
async function submit(event:FormEvent){event.preventDefault();setError("");const project=projects.find(item=>item.id===projectId);if(!project){setError("Choose a project first.");return;}if(!description.trim()||!Number.isFinite(Number(amount))||Number(amount)<=0){setError("Enter a description and a valid amount greater than zero.");return;}setSaving(true);try{const financeResponse=await fetch("/api/data/finance",{method:"POST",headers:{"Content-Type":"application/json"},credentials:"include",body:JSON.stringify({id:`FIN-${crypto.randomUUID().slice(0,8).toUpperCase()}`,project_id:project.id,type,category,description:description.trim(),amount:Number(amount),currency,status,transaction_date:date,created_by_name:"Mason & Arc Owner"})});const financeData=await financeResponse.json().catch(()=>({}));if(!financeResponse.ok)throw new Error(financeData.error||"Could not save finance entry.");if(contract!==""||budget!==""){const projectResponse=await fetch("/api/data/projects",{method:"PATCH",headers:{"Content-Type":"application/json"},credentials:"include",body:JSON.stringify({id:project.id,contract_value:contract===""?null:Number(contract),budget:budget===""?null:Number(budget),financial_currency:currency})});const projectData=await projectResponse.json().catch(()=>({}));if(!projectResponse.ok)throw new Error(projectData.error||"Finance entry was saved, but the project baseline could not be updated.");}router.push(`/app/admin/projects/${project.id}/finance`);router.refresh();}catch(cause){setError(cause instanceof Error?cause.message:"Could not save finance entry.");}finally{setSaving(false)}}
return <main className="min-h-screen bg-[#080808] text-white"><div className="mx-auto max-w-4xl px-5 py-7 sm:px-8"><Link href="/app/admin/finance" className="inline-flex items-center gap-2 text-sm text-white/45"><ArrowLeft size={15}/>Back to Finance</Link><h1 className="mt-7 text-3xl font-semibold sm:text-4xl">Finance Entry</h1><p className="mt-2 text-sm text-white/40">Record a shared transaction and update the project baseline when needed.</p>{error&&<p role="alert" className="mt-5 rounded-xl border border-red-400/30 bg-red-500/10 px-4 py-3 text-sm text-red-200">{error}</p>}<form onSubmit={submit} className="mt-7 space-y-5"><Card title="Transaction"><div className="grid gap-4 md:grid-cols-2"><Select label="Project" value={projectId} onChange={setProjectId} options={projects.map(project=>({value:project.id,label:`${project.code} — ${project.name}`}))}/><Select label="Type" value={type} onChange={value=>{setType(value);setStatus(value==="Income"?"Received":"Paid")}} options={[{value:"Income",label:"Income"},{value:"Expense",label:"Expense"}]}/><Select label="Category" value={category} onChange={setCategory} options={categories.map(value=>({value,label:value}))}/><Input label="Description" value={description} onChange={setDescription} required/><Input label="Amount" value={amount} onChange={setAmount} type="number" min="0.01" required/><Select label="Currency" value={currency} onChange={setCurrency} options={["EGP","USD","EUR"].map(value=>({value,label:value}))}/><Input label="Date" value={date} onChange={setDate} type="date"/><Select label="Status" value={status} onChange={setStatus} options={(type==="Income"?["Received","Pending"]:["Paid","Pending"]).map(value=>({value,label:value}))}/></div></Card><Card title="Project Financial Baseline"><div className="grid gap-4 md:grid-cols-2"><Input label="Contract Value" value={contract} onChange={setContract} type="number" min="0" placeholder="Optional"/><Input label="Project Budget" value={budget} onChange={setBudget} type="number" min="0" placeholder="Optional"/></div><p className="mt-3 text-xs text-white/30">These values are saved to the project, not this browser.</p></Card><div className="flex justify-end"><button disabled={saving} className="inline-flex items-center gap-2 rounded-xl bg-white px-5 py-3 text-sm font-medium text-black disabled:opacity-50"><Save size={16}/>{saving?"Saving…":"Save Finance Entry"}</button></div></form></div></main>}
function Card({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-2xl border border-white/10 bg-white/[.03] p-5 sm:p-6"><h2 className="text-xs uppercase tracking-[.18em] text-white/40">{title}</h2><div className="mt-5">{children}</div></section>};function Input({label,value,onChange,type="text",required=false,min,placeholder}:{label:string;value:string;onChange:(value:string)=>void;type?:string;required?:boolean;min?:string;placeholder?:string}){return <label className="text-sm"><span className="mb-2 block text-white/55">{label}</span><input className="input" type={type} min={min} value={value} onChange={event=>onChange(event.target.value)} required={required} placeholder={placeholder}/></label>};function Select({label,value,onChange,options}:{label:string;value:string;onChange:(value:string)=>void;options:Array<{value:string;label:string}>}){return <label className="text-sm"><span className="mb-2 block text-white/55">{label}</span><select className="input" value={value} onChange={event=>onChange(event.target.value)}>{options.map(option=><option key={option.value} value={option.value}>{option.label}</option>)}</select></label>};
export default function NewFinancePage(){return <Suspense fallback={<main className="min-h-screen bg-[#080808] p-8 text-white">Loading finance…</main>}><FinanceForm/><style jsx global>{`.input{width:100%;border-radius:12px;border:1px solid rgba(255,255,255,.14);background:#111;padding:12px;color:#fff;outline:none}.input:focus{border-color:rgba(255,255,255,.4)}.input option{background:#111;color:#fff}`}</style></Suspense>}
