"use client";

import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import { FormEvent, useEffect, useState } from "react";
import { ArrowLeft, Save, Trash2 } from "lucide-react";

type Client = { id:string; code:string; name:string; company:string|null; contact_email:string|null; contact_phone:string|null; address:string|null; notes:string|null; active:boolean };
const blank: Client = { id:"", code:"", name:"", company:"", contact_email:"", contact_phone:"", address:"", notes:"", active:true };

export default function EditClientPage() {
  const params = useParams<{id:string}>(); const router = useRouter(); const id = params?.id || "";
  const [client, setClient] = useState<Client>(blank); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  useEffect(() => { void (async () => { const response=await fetch("/api/data/clients",{cache:"no-store",credentials:"include"}); const data=await response.json().catch(()=>({})); const found=(data.data||[]).find((item:Client)=>item.id===id); if(!response.ok) setError(data.error||"Could not load client."); else if(!found) setError("Client not found."); else setClient({...blank,...found}); setLoading(false); })(); },[id]);
  async function save(event:FormEvent) { event.preventDefault(); setSaving(true); setError(""); const response=await fetch("/api/data/clients",{method:"PATCH",headers:{"Content-Type":"application/json"},credentials:"include",body:JSON.stringify(client)}); const data=await response.json().catch(()=>({})); setSaving(false); if(!response.ok){setError(data.error||"Could not save client.");return;} router.push(`/app/admin/clients/${id}`); router.refresh(); }
  async function remove() { if(!window.confirm(`Delete ${client.name}? This cannot be undone.`))return; const response=await fetch(`/api/data/clients?id=${encodeURIComponent(id)}`,{method:"DELETE",credentials:"include"}); const data=await response.json().catch(()=>({})); if(!response.ok){setError(data.error||"Could not delete client.");return;} router.push("/app/admin/clients"); router.refresh(); }
  const update=(key:keyof Client,value:string|boolean)=>setClient(current=>({...current,[key]:value}));
  if(loading)return <main className="min-h-screen bg-[#080808] p-8 text-white">Loading client…</main>;
  return <main className="min-h-screen bg-[#080808] px-5 py-7 text-white sm:px-8"><div className="mx-auto max-w-3xl"><Link href="/app/admin/clients" className="inline-flex items-center gap-2 text-sm text-white/50"><ArrowLeft size={15}/>Clients</Link><div className="mt-7 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs uppercase tracking-[.2em] text-white/35">Studio CRM</p><h1 className="mt-2 text-3xl font-semibold">Edit Client</h1></div><button onClick={() => void remove()} className="inline-flex items-center gap-2 rounded-xl border border-red-400/30 px-4 py-3 text-sm text-red-200"><Trash2 size={16}/>Delete</button></div>{error&&<p role="alert" className="mt-5 rounded-xl border border-red-400/30 bg-red-500/10 px-4 py-3 text-sm text-red-200">{error}</p>}<form onSubmit={save} className="mt-7 space-y-5 rounded-2xl border border-white/10 bg-white/[.03] p-5 sm:p-6"><div className="grid gap-4 sm:grid-cols-2"><Field label="Client name" value={client.name} onChange={value=>update("name",value)} required/><Field label="Company" value={client.company||""} onChange={value=>update("company",value)}/><Field label="Email" type="email" value={client.contact_email||""} onChange={value=>update("contact_email",value)}/><Field label="Phone" value={client.contact_phone||""} onChange={value=>update("contact_phone",value)}/><Field label="Address" value={client.address||""} onChange={value=>update("address",value)}/><label className="text-sm"><span className="mb-2 block text-white/60">Status</span><select value={client.active?"Active":"Inactive"} onChange={event=>update("active",event.target.value==="Active")} className="input"><option>Active</option><option>Inactive</option></select></label></div><label className="block text-sm"><span className="mb-2 block text-white/60">Internal notes</span><textarea value={client.notes||""} onChange={event=>update("notes",event.target.value)} rows={5} className="input resize-y"/></label><div className="flex justify-end"><button disabled={saving||!client.name.trim()} className="inline-flex items-center gap-2 rounded-xl bg-white px-5 py-3 text-sm font-medium text-black disabled:opacity-50"><Save size={16}/>{saving?"Saving…":"Save Changes"}</button></div></form></div><style jsx>{`.input{width:100%;border-radius:12px;border:1px solid rgba(255,255,255,.14);background:#111;padding:12px;color:#fff;outline:none}`}</style></main>;
}
function Field({label,value,onChange,type="text",required=false}:{label:string;value:string;onChange:(value:string)=>void;type?:string;required?:boolean}){return <label className="text-sm"><span className="mb-2 block text-white/60">{label}</span><input required={required} type={type} value={value} onChange={event=>onChange(event.target.value)} className="input"/></label>}
