"use client";
import Link from "next/link";
import { useEffect,useMemo,useState } from "react";
import { ArrowDownRight,ArrowUpRight,BarChart3,CircleDollarSign,FileText,Plus,RefreshCw,Wallet } from "lucide-react";
import { getFinanceTransactions,getStudioExpenses,getStudioIncome,getStudioProfit,getProjectBudgets,getBudgetVsActual,getInvoices,getOverdueInvoices,formatAmount,type FinanceTransaction } from "./financeStore";
import { getActiveProjects } from "@/lib/core/projectStore";

export default function FinancePage(){
 const [tick,setTick]=useState(0); const [search,setSearch]=useState(""); const [filter,setFilter]=useState("All");
 useEffect(()=>{const t=window.setInterval(()=>setTick(x=>x+1),1500);return()=>window.clearInterval(t)},[]);
 const transactions=getFinanceTransactions(); const income=getStudioIncome(); const expenses=getStudioExpenses(); const profit=getStudioProfit(); const pending=transactions.filter(x=>x.status==="Pending").reduce((n,x)=>n+x.amount,0); const invoices=getInvoices(); const overdue=getOverdueInvoices(); const projects=getActiveProjects();
 const filtered=useMemo(()=>transactions.filter(x=>(filter==="All"||filter===x.type||(filter==="Pending"&&x.status==="Pending"))&&(`${x.id} ${x.projectName} ${x.description} ${x.category}`.toLowerCase().includes(search.toLowerCase()))),[transactions,filter,search]);
 return <main className="min-h-screen bg-[#080808] text-white"><div className="mx-auto max-w-[1500px] px-6 py-8 lg:px-10">
  <div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-xs uppercase tracking-[.28em] text-white/30">Mason & Arc / Finance OS</p><h1 className="mt-2 text-4xl font-semibold tracking-tight">Finance 2.0</h1><p className="mt-2 text-sm text-white/40">Budget, actual cost, payments, profitability and invoices.</p></div><div className="flex gap-2"><button onClick={()=>setTick(x=>x+1)} className="rounded-full border border-white/10 px-4 py-3 text-sm"><RefreshCw size={15}/></button><Link href="/app/admin/finance/new" className="inline-flex items-center gap-2 rounded-full bg-white px-5 py-3 text-sm font-medium text-black"><Plus size={16}/>Add Transaction</Link></div></div>
  <div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{[["Revenue",income,"+"],["Actual Costs",expenses,"-"],["Net Profit",profit,""],["Pending",pending,""],["Overdue Invoices",overdue.length,""]].map(([label,value,prefix])=><div key={String(label)} className="rounded-3xl border border-white/10 bg-white/[.025] p-6"><p className="text-xs uppercase tracking-[.18em] text-white/30">{label}</p><p className="mt-5 text-2xl font-semibold">{label==="Overdue Invoices"?value:`${prefix}${Number(value).toLocaleString()} EGP`}</p></div>)}</div>
  <section className="mt-6 grid gap-4 lg:grid-cols-3"><div className="lg:col-span-2 rounded-3xl border border-white/10 bg-white/[.025] p-6"><div className="flex items-center justify-between"><div><p className="text-xs uppercase tracking-[.18em] text-white/30">Studio Profitability</p><p className="mt-2 text-3xl font-semibold">{income?Math.round((profit/income)*100):0}%</p><p className="mt-1 text-sm text-white/35">Net margin</p></div><CircleDollarSign className="text-white/30"/></div><div className="mt-7 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full bg-white" style={{width:`${income?Math.max(0,Math.min(100,Math.round((profit/income)*100))):0}%`}}/></div><div className="mt-4 grid grid-cols-3 gap-3 text-sm"><div><p className="text-white/30">Income</p><p className="mt-1">{formatAmount(income,"EGP")}</p></div><div><p className="text-white/30">Expenses</p><p className="mt-1">{formatAmount(expenses,"EGP")}</p></div><div><p className="text-white/30">Profit</p><p className="mt-1">{formatAmount(profit,"EGP")}</p></div></div></div><div className="rounded-3xl border border-white/10 bg-white/[.025] p-6"><p className="text-xs uppercase tracking-[.18em] text-white/30">Invoices</p><p className="mt-5 text-3xl font-semibold">{invoices.length}</p><p className="mt-1 text-sm text-white/35">Total invoices</p><div className="mt-5 space-y-2 text-xs text-white/40"><div className="flex justify-between"><span>Overdue</span><span>{overdue.length}</span></div><div className="flex justify-between"><span>Pending transactions</span><span>{transactions.filter(x=>x.status==="Pending").length}</span></div></div></div></section>
  <section className="mt-6 rounded-3xl border border-white/10 bg-white/[.025] p-6"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs uppercase tracking-[.18em] text-white/30">Project Control</p><h2 className="mt-2 text-xl font-medium">Budget vs Actual</h2></div><div className="flex gap-2"><Link href="/app/admin/finance/new" className="rounded-full border border-white/10 px-4 py-2 text-xs">New Transaction</Link></div></div><div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{projects.map(p=>{const x=getBudgetVsActual(p.id);return <Link key={p.id} href={`/app/admin/projects/${p.id}/finance`} className="rounded-2xl border border-white/8 p-5 hover:bg-white/[.03]"><div className="flex justify-between"><span className="text-xs text-white/40">{p.code}</span><BarChart3 size={16} className="text-white/25"/></div><p className="mt-3 font-medium">{p.name}</p><div className="mt-4 grid grid-cols-2 gap-3 text-xs"><div><span className="text-white/25">Budget</span><p className="mt-1">{formatAmount(x.budget,"EGP")}</p></div><div><span className="text-white/25">Actual</span><p className="mt-1">{formatAmount(x.actualCost,"EGP")}</p></div></div><div className="mt-4 h-1.5 rounded-full bg-white/10"><div className="h-full bg-white" style={{width:`${Math.min(100,x.utilization)}%`}}/></div><p className="mt-2 text-[10px] text-white/25">{x.utilization}% of budget used</p></Link>})}</div></section>
  <section className="mt-6 overflow-hidden rounded-3xl border border-white/10 bg-white/[.025]"><div className="flex flex-col gap-4 border-b border-white/10 p-6 md:flex-row md:items-center md:justify-between"><div><p className="text-xs uppercase tracking-[.18em] text-white/30">Transactions</p><p className="mt-1 text-sm text-white/35">All financial activity</p></div><div className="flex gap-2"><div className="flex rounded-xl border border-white/10 p-1">{["All","Income","Expense","Pending"].map(x=><button key={x} onClick={()=>setFilter(x)} className={`rounded-lg px-3 py-2 text-xs ${filter===x?"bg-white text-black":"text-white/35"}`}>{x}</button>)}</div><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search..." className="rounded-xl border border-white/10 bg-transparent px-3 text-xs outline-none"/></div></div><div className="divide-y divide-white/6">{filtered.slice(0,50).map(x=><div key={x.id} className="flex flex-col gap-3 p-5 md:flex-row md:items-center md:justify-between"><div className="flex items-start gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-xl border border-white/10">{x.type==="Income"?<ArrowUpRight size={15}/>:<ArrowDownRight size={15}/>}</div><div><p className="text-sm">{x.description}</p><p className="mt-1 text-xs text-white/30">{x.id} · {x.projectName} · {x.category} · {x.date}</p></div></div><div className="text-right"><p className={x.type==="Income"?"text-emerald-300/80":"text-red-300/75"}>{x.type==="Income"?"+":"-"}{formatAmount(x.amount,x.currency)}</p><p className="mt-1 text-[10px] text-white/30">{x.status}</p></div></div>)}{filtered.length===0&&<div className="p-12 text-center text-sm text-white/30">No transactions found.</div>}</div></section>
 </div></main>
}
