import { NextResponse } from "next/server";
import { audit, requireServerUser } from "@/lib/server/auth";
import { query, withTransaction } from "@/lib/server/db";

export const runtime="nodejs";
type IssueInput={title?:unknown;description?:unknown;location?:unknown;priority?:unknown};
const clean=(value:unknown,limit=500)=>String(value||"").trim().slice(0,limit);

export async function POST(request:Request){try{const user=await requireServerUser(["Owner","Manager","Engineer"]);const body=await request.json();const projectId=clean(body?.project_id,100);const reportDate=clean(body?.report_date,10);if(!projectId||!reportDate)return NextResponse.json({error:"Project and report date are required."},{status:400});if(user.role==="Engineer"){const access=await query(`SELECT 1 FROM projects p WHERE p.id=$1 AND (p.project_manager_id=$2 OR EXISTS(SELECT 1 FROM project_memberships pm WHERE pm.project_id=p.id AND pm.user_id=$2 AND pm.active=true)) LIMIT 1`,[projectId,user.id]);if(!access.rows[0])throw new Error("FORBIDDEN")}const project=await query(`SELECT name FROM projects WHERE id=$1 LIMIT 1`,[projectId]);if(!project.rows[0])return NextResponse.json({error:"Project not found."},{status:404});const reportId=`SITE-${crypto.randomUUID().slice(0,8).toUpperCase()}`;const issues=Array.isArray(body?.issues)?(body.issues as IssueInput[]).slice(0,25):[];await withTransaction(async(client)=>{await client.query(`INSERT INTO site_reports(id,project_id,project_name,report_date,visit_type,weather,engineer_name,summary,created_by_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)`,[reportId,projectId,project.rows[0].name,reportDate,clean(body?.visit_type,100)||"Site Visit",clean(body?.weather,100)||null,user.name,clean(body?.summary,10000),user.id]);for(const issue of issues){const title=clean(issue.title,240);if(!title)continue;await client.query(`INSERT INTO site_issues(id,project_id,report_id,title,description,location,priority,status,assigned_to_id,assigned_to_name) VALUES($1,$2,$3,$4,$5,$6,$7,'Open',$8,$9)`,[`ISS-${crypto.randomUUID().slice(0,8).toUpperCase()}`,projectId,reportId,title,clean(issue.description,5000),clean(issue.location,300),["Low","Medium","High","Urgent"].includes(clean(issue.priority,20))?clean(issue.priority,20):"Medium",user.id,user.name])}});await audit("site_report.created","site_reports",reportId,{projectId,issues:issues.length});return NextResponse.json({id:reportId},{status:201})}catch(error){const message=error instanceof Error?error.message:"";return NextResponse.json({error:message==="UNAUTHENTICATED"?"Authentication required.":message==="FORBIDDEN"?"You are not assigned to this project.":"Could not save site report."},{status:message==="UNAUTHENTICATED"?401:message==="FORBIDDEN"?403:500})}}
