"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { Camera, ClipboardList, ExternalLink, ShieldAlert, CheckCircle2 } from "lucide-react";
import { getSiteReports, updateSiteIssue, createTaskFromSiteIssue, type SiteReport } from "@/app/app/engineer/site/siteStore";

export default function AdminSitePage() {
  const [reports, setReports] = useState<SiteReport[]>([]);
  const refresh = () => setReports(getSiteReports());
  useEffect(() => { refresh(); const t = window.setInterval(refresh, 1500); return () => window.clearInterval(t); }, []);
  const issues = useMemo(() => reports.flatMap((r) => r.issues.map((i) => ({ ...i, reportId: r.id, project: r.project }))), [reports]);
  const open = issues.filter((i) => i.status !== "Resolved");
  const urgent = open.filter((i) => i.priority === "Urgent");
  return <div className="min-h-screen bg-[#f6f6f4] px-4 py-7 text-[#111] md:px-8"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-xs uppercase tracking-[.25em] text-black/40">Mason & Arc / Operations</p><h1 className="mt-2 text-4xl font-semibold tracking-tight">Site Intelligence</h1><p className="mt-2 text-sm text-black/50">Monitor reports, field evidence, open issues and resolution flow.</p></div><Link href="/app/engineer/site/new" className="rounded-full bg-black px-5 py-3 text-sm text-white">+ New Site Report</Link></div>
  <div className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Kpi icon={<ClipboardList size={17}/>} label="Reports" value={reports.length}/><Kpi icon={<Camera size={17}/>} label="Photos" value={reports.reduce((n,r)=>n+r.photos.length,0)}/><Kpi icon={<ShieldAlert size={17}/>} label="Open Issues" value={open.length}/><Kpi icon={<CheckCircle2 size={17}/>} label="Resolved" value={issues.length-open.length}/></div>
  <div className="mt-7 grid gap-7 lg:grid-cols-[1.4fr_1fr]"><section className="rounded-2xl border border-black/8 bg-white p-6"><div className="flex items-center justify-between"><div><p className="text-xs uppercase tracking-wider text-black/40">Issue Queue</p><h2 className="mt-2 text-2xl font-semibold">Open Site Issues</h2></div><span className="rounded-full bg-red-50 px-3 py-1 text-xs text-red-700">{urgent.length} urgent</span></div><div className="mt-5 space-y-3">{open.length===0?<Empty/>:open.map((issue)=><div key={`${issue.reportId}-${issue.id}`} className="rounded-xl border border-black/8 p-5"><div className="flex flex-col justify-between gap-4 md:flex-row"><div><div className="flex flex-wrap gap-2"><h3 className="font-medium">{issue.title}</h3><span className="text-xs text-black/40">{issue.priority}</span></div><p className="mt-2 text-xs text-black/45">{issue.location} · {issue.assignedTo || "Unassigned"} · {issue.project}</p><p className="mt-2 text-sm text-black/55">{issue.description}</p></div><div className="flex flex-wrap gap-2"><button onClick={()=>{updateSiteIssue(issue.reportId,issue.id,{status:issue.status==="Open"?"In Progress":"Resolved"});refresh();}} className="rounded-full bg-black px-4 py-2 text-xs text-white">{issue.status==="Open"?"Start":"Resolve"}</button>{!issue.taskId&&<button onClick={()=>{createTaskFromSiteIssue(issue.reportId,issue.id);refresh();}} className="rounded-full border border-black/10 px-4 py-2 text-xs">Create Task</button>}{issue.taskId&&<Link href={`/app/admin/tasks/${issue.taskId}`} className="rounded-full border border-black/10 px-4 py-2 text-xs">Open Task</Link>}</div></div></div>)}</div></section>
  <section className="rounded-2xl border border-black/8 bg-white p-6"><p className="text-xs uppercase tracking-wider text-black/40">Recent Reports</p><h2 className="mt-2 text-2xl font-semibold">Field History</h2><div className="mt-5 space-y-3">{reports.slice(0,10).map(r=><div key={r.id} className="rounded-xl border border-black/8 p-4"><div className="flex justify-between gap-3"><div><p className="text-[10px] uppercase tracking-wider text-black/40">{r.id} · {r.date}</p><p className="mt-2 font-medium">{r.visitType}</p><p className="mt-1 text-xs text-black/45">{r.engineer}</p></div><span className="text-xs text-black/40">{r.photos.length} photos</span></div>{r.summary&&<p className="mt-3 text-sm text-black/50">{r.summary}</p>}</div>)}{reports.length===0&&<Empty/>}</div><Link href="/app/engineer/site" className="mt-5 inline-flex items-center gap-2 text-xs underline">Open engineer site workspace <ExternalLink size={12}/></Link></section></div></div></div>;
}
function Kpi({icon,label,value}:{icon:React.ReactNode;label:string;value:number}){return <div className="rounded-2xl border border-black/8 bg-white p-5"><div className="flex justify-between text-black/40">{icon}<span className="text-xs uppercase tracking-wider">{label}</span></div><p className="mt-3 text-3xl font-semibold">{value}</p></div>}
function Empty(){return <div className="rounded-xl border border-dashed border-black/10 p-10 text-center text-sm text-black/40">Nothing here yet.</div>}
