import { NextResponse } from "next/server";
import { audit, requireServerUser, type ServerUser } from "@/lib/server/auth";
import { query } from "@/lib/server/db";
export const runtime = "nodejs"; export const dynamic = "force-dynamic";
type Context = { params: Promise<{ id: string }> }; const text=(v:unknown,n=4000)=>typeof v==="string"?v.trim().slice(0,n):""; const date=(v:unknown)=>/^\d{4}-\d{2}-\d{2}$/.test(text(v,10))?text(v,10):null; const num=(v:unknown,min:number,max:number)=>Number.isFinite(Number(v))?Math.min(max,Math.max(min,Number(v))):0;
async function access(user:ServerUser,projectId:string){if(user.role==="Owner"||user.role==="Manager")return true;return Boolean((await query("SELECT 1 FROM project_memberships WHERE project_id=$1 AND user_id=$2 AND active=true",[projectId,user.id])).rows[0]);}
async function inProject(table:"project_wbs_nodes"|"project_schedule_activities",id:string,projectId:string){return Boolean((await query(`SELECT 1 FROM ${table} WHERE id=$1 AND project_id=$2`,[id,projectId])).rows[0]);}
function fail(e:unknown){const m=e instanceof Error?e.message:"";if(m==="UNAUTHENTICATED")return NextResponse.json({error:"Authentication required."},{status:401});if(m==="FORBIDDEN")return NextResponse.json({error:"You do not have permission to access this project."},{status:403});if((e as {code?:string}).code==="23505")return NextResponse.json({error:"This code or dependency already exists in the project."},{status:409});console.error(e);return NextResponse.json({error:"Construction management request failed."},{status:500});}
export async function GET(_:Request,{params}:Context){try{const {id}=await params;const user=await requireServerUser(["Owner","Manager","Engineer"]);if(!(await access(user,id)))throw new Error("FORBIDDEN");const [wbs,activities,dependencies]=await Promise.all([query("SELECT * FROM project_wbs_nodes WHERE project_id=$1 ORDER BY display_order,created_at",[id]),query("SELECT * FROM project_schedule_activities WHERE project_id=$1 ORDER BY display_order,created_at",[id]),query("SELECT * FROM project_activity_dependencies WHERE project_id=$1 ORDER BY created_at",[id])]);return NextResponse.json({wbs:wbs.rows,activities:activities.rows,dependencies:dependencies.rows});}catch(e){return fail(e);}}
export async function POST(request:Request,{params}:Context){try{const {id:projectId}=await params;const user=await requireServerUser(["Owner","Manager","Engineer"]);if(!(await access(user,projectId)))throw new Error("FORBIDDEN");const body=await request.json() as Record<string,unknown>;const kind=text(body.kind,30);
if(kind==="wbs"){const code=text(body.code,80),name=text(body.name,200),parent=text(body.parent_id,100)||null;if(!code||!name)return NextResponse.json({error:"WBS code and name are required."},{status:400});if(parent&&!(await inProject("project_wbs_nodes",parent,projectId)))return NextResponse.json({error:"Parent WBS was not found."},{status:400});const r=await query(`INSERT INTO project_wbs_nodes(id,project_id,parent_id,code,name,discipline,planned_start,planned_finish,progress_percent,budget,notes,display_order) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,(SELECT COALESCE(MAX(display_order)+1,0) FROM project_wbs_nodes WHERE project_id=$2)) RETURNING *`,[`WBS-${crypto.randomUUID().slice(0,8)}`,projectId,parent,code,name,text(body.discipline,100),date(body.planned_start),date(body.planned_finish),num(body.progress_percent,0,100),body.budget==null||body.budget===""?null:num(body.budget,0,999999999999),text(body.notes,12000)]);await audit("construction.wbs.created","ProjectWbs",String(r.rows[0].id),{projectId,actor:user.id});return NextResponse.json({data:r.rows[0]},{status:201});}
if(kind==="activity"){const code=text(body.activity_code,80),name=text(body.name,200),wbs=text(body.wbs_id,100)||null;if(!code||!name)return NextResponse.json({error:"Activity ID and name are required."},{status:400});if(wbs&&!(await inProject("project_wbs_nodes",wbs,projectId)))return NextResponse.json({error:"WBS was not found."},{status:400});const status=["Not Started","In Progress","Completed","On Hold"].includes(text(body.status,30))?text(body.status,30):"Not Started";const priority=["Low","Medium","High","Critical"].includes(text(body.priority,20))?text(body.priority,20):"Medium";const r=await query(`INSERT INTO project_schedule_activities(id,project_id,wbs_id,activity_code,name,description,discipline,responsible_name,planned_duration_days,planned_start,planned_finish,progress_percent,status,priority,is_milestone,display_order) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,(SELECT COALESCE(MAX(display_order)+1,0) FROM project_schedule_activities WHERE project_id=$2)) RETURNING *`,[`ACT-${crypto.randomUUID().slice(0,8)}`,projectId,wbs,code,name,text(body.description,12000),text(body.discipline,100),text(body.responsible_name,200),num(body.planned_duration_days,0,36500),date(body.planned_start),date(body.planned_finish),num(body.progress_percent,0,100),status,priority,Boolean(body.is_milestone)]);await audit("construction.activity.created","ProjectActivity",String(r.rows[0].id),{projectId,actor:user.id});return NextResponse.json({data:r.rows[0]},{status:201});}
if(kind==="dependency"){const pre=text(body.predecessor_activity_id,100),next=text(body.successor_activity_id,100);if(!pre||!next||pre===next||!(await inProject("project_schedule_activities",pre,projectId))||!(await inProject("project_schedule_activities",next,projectId)))return NextResponse.json({error:"Choose two different project activities."},{status:400});const type=["FS","SS","FF","SF"].includes(text(body.relationship_type,2))?text(body.relationship_type,2):"FS";const r=await query("INSERT INTO project_activity_dependencies(id,project_id,predecessor_activity_id,successor_activity_id,relationship_type,lag_days) VALUES($1,$2,$3,$4,$5,$6) RETURNING *",[`DEP-${crypto.randomUUID().slice(0,8)}`,projectId,pre,next,type,num(body.lag_days,-3650,3650)]);return NextResponse.json({data:r.rows[0]},{status:201});}return NextResponse.json({error:"Unknown construction record type."},{status:400});}catch(e){return fail(e);}}
export async function DELETE(request:Request,{params}:Context){try{const {id:projectId}=await params;const user=await requireServerUser(["Owner","Manager"]);if(!(await access(user,projectId)))throw new Error("FORBIDDEN");const url=new URL(request.url),kind=url.searchParams.get("kind"),id=url.searchParams.get("id");const table=kind==="wbs"?"project_wbs_nodes":kind==="activity"?"project_schedule_activities":kind==="dependency"?"project_activity_dependencies":"";if(!table||!id)return NextResponse.json({error:"Record type and ID are required."},{status:400});const r=await query(`DELETE FROM ${table} WHERE id=$1 AND project_id=$2 RETURNING id`,[id,projectId]);if(!r.rows[0])return NextResponse.json({error:"Record not found."},{status:404});await audit("construction.record.deleted","Construction",id,{projectId,actor:user.id,kind});return NextResponse.json({ok:true});}catch(e){return fail(e);}}
