"use client";

import Image from "next/image";
import Link from "next/link";
import { localizedText, localizedYear, projectCopy, useLocale } from "@/components/i18n/LocaleProvider";
import type { WebsiteProject, WebsiteProjectSectionImage } from "@/lib/server/websiteProjects";

function SectionImages({ images, title, locale, layout }: { images: WebsiteProjectSectionImage[]; title: string; locale: "en" | "ar" | "it"; layout: string }) {
  if (!images.length) return null;
  return <div className={`grid gap-5 lg:col-span-12 ${layout === "gallery" ? "md:grid-cols-3" : "md:grid-cols-2"}`}>{images.map((image, index) => {
    const caption = localizedText(image.caption, locale); const alt = localizedText(image.alt_text, locale) || `${title} — ${index + 1}`;
    const span = image.layout === "full_bleed" || (images.length === 1 && layout !== "gallery") ? "md:col-span-2" : "";
    const ratio = image.layout === "portrait" ? "aspect-[3/4]" : image.layout === "drawing" ? "aspect-[16/10] bg-white" : "aspect-[4/3]";
    return <figure key={image.id} className={span}><div className={`relative overflow-hidden ${ratio}`}><Image src={image.image_url} alt={alt} fill sizes={span ? "100vw" : "(min-width: 768px) 50vw, 100vw"} className={image.layout === "drawing" ? "object-contain" : "object-cover"} /></div>{caption && <figcaption className="mt-3 text-[10px] leading-5 tracking-wide opacity-55">{caption}</figcaption>}</figure>;
  })}</div>;
}

export default function ProjectDetail({ project }: { project: WebsiteProject }) {
  const { locale, copy } = useLocale(); const translated = projectCopy(project, locale); const sections = project.content_sections.filter((section) => section.is_visible);
  return <main className="bg-black text-white">
    <section className="relative min-h-[100svh] overflow-hidden"><Image src={project.image_url} alt={translated.title} fill priority sizes="100vw" className="object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-black via-black/25 to-black/10" /><div className="relative z-10 flex min-h-[100svh] flex-col justify-end px-6 pb-10 md:px-10 md:pb-14 lg:px-16"><div className="flex flex-col gap-8 lg:flex-row lg:items-end lg:justify-between"><div><p className="mb-5 text-[9px] uppercase tracking-[.3em] text-white/60">{translated.category}</p><h1 className={`max-w-[1200px] uppercase leading-[.82] tracking-[-.035em] ${locale === "ar" ? "font-[var(--font-arabic)] text-[clamp(3.6rem,10vw,9.3rem)] font-light" : "font-[var(--font-display)] text-[clamp(4rem,11vw,9.4rem)]"}`}>{translated.title}</h1></div><div className="text-[10px] uppercase tracking-[.2em] text-white/65 lg:text-end"><p>{translated.location}</p><p className="mt-2">{localizedYear(project.year, locale)}</p></div></div></div></section>
    <section className="px-6 py-24 md:px-10 md:py-32 lg:px-16"><div className="grid gap-12 lg:grid-cols-12"><p className="text-[9px] uppercase tracking-[.3em] text-white/40 lg:col-span-3">01 — {copy.overview}</p><p className={`leading-[1.12] tracking-[-.025em] sm:text-[32px] md:text-[46px] lg:col-span-8 lg:col-start-5 ${locale === "ar" ? "text-[27px] md:leading-[1.35]" : "text-[25px]"}`}>{translated.description}</p></div></section>
    <section className="bg-[#f2f2f0] px-6 py-16 text-black md:px-10 lg:px-16"><div className="grid gap-8 sm:grid-cols-3"><div><p className="text-xs uppercase tracking-[.2em] text-black/45">{copy.type}</p><p className="mt-3 text-lg">{translated.category}</p></div><div><p className="text-xs uppercase tracking-[.2em] text-black/45">{copy.location}</p><p className="mt-3 text-lg">{translated.location}</p></div><div><p className="text-xs uppercase tracking-[.2em] text-black/45">{copy.timeline}</p><p className="mt-3 text-lg">{localizedYear(project.year, locale)}</p></div></div></section>
    {sections.map((section, index) => { const title = localizedText(section.title, locale); const body = localizedText(section.body, locale); const eyebrow = localizedText(section.eyebrow, locale) || String(index + 2).padStart(2, "0"); const statement = localizedText(section.hero_statement, locale); const light = index % 2 === 1; return <section key={section.id} className={`${light ? "bg-[#f2f2f0] text-black" : "bg-black text-white"} px-6 py-24 md:px-10 md:py-32 lg:px-16`}><div className="grid gap-12 lg:grid-cols-12 lg:gap-y-16"><p className={`text-[9px] uppercase tracking-[.3em] lg:col-span-3 ${light ? "text-black/45" : "text-white/40"}`}>{eyebrow}{title ? ` — ${title}` : ""}</p><div className="lg:col-span-8 lg:col-start-5">{title && <h2 className={`leading-[.9] tracking-[-.045em] ${locale === "ar" ? "text-[48px] font-light sm:text-[64px] md:text-[82px]" : "font-[var(--font-display)] text-[clamp(3.6rem,8vw,6.4rem)] uppercase"}`}>{title}</h2>}{body && <p className={`mt-10 max-w-4xl whitespace-pre-line leading-[1.5] tracking-[-.015em] ${locale === "ar" ? "text-[22px] md:text-[30px] md:leading-[1.65]" : "text-[20px] md:text-[28px]"}`}>{body}</p>}</div>{statement && <div className="py-8 lg:col-span-10 lg:col-start-3"><p className={`max-w-6xl whitespace-pre-line font-[var(--font-display)] text-[clamp(3.5rem,10vw,10rem)] uppercase leading-[.8] tracking-[-.055em] ${locale === "ar" ? "font-[var(--font-arabic)] leading-[1.05]" : ""}`}>{statement}</p></div>}<SectionImages images={section.images} title={title || translated.title} locale={locale} layout={section.layout} /></div></section>; })}
    {!sections.length && project.gallery.length > 0 && <section className="px-6 py-24 md:px-10 md:py-32 lg:px-16"><div className="grid gap-6 md:grid-cols-2">{project.gallery.map((image, index) => <div key={`${image}-${index}`} className={`relative overflow-hidden ${index === 0 ? "md:col-span-2 aspect-[16/9]" : "aspect-[4/3]"}`}><Image src={image} alt={`${translated.title} — ${index + 1}`} fill sizes="100vw" className="object-cover" /></div>)}</div></section>}
    <footer className="border-t border-white/15 px-6 py-10 md:px-10 lg:px-16"><Link href="/projects" className="text-[9px] uppercase tracking-[.25em] text-white/60">← {copy.allProjects}</Link></footer>
  </main>;
}
